name: Load Testing for Joyfill App

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install locust

      - name: Run Load Test
        run: |
          locust -f tests/locustfile.py --headless --users 10 --spawn-rate 10 --run-time 2m --host http://localhost:5000
